language: node_js
node_js:
  - 'stable'
  - '5'
  - '5.0'
  - '4'
  - '4.0'

before_script:
  - 'psql -U postgres -c "create database benfucius_test;"'

env:
  globals:
    - 'BENFUCIUS_DB=postgres://postgres:@localhost/benfucius_test'
